#!/bin/bash

set -eu

juju-log "writing varnish daemon config"
port=`config-get port`
cat > /etc/default/varnish <<EOF
START=yes
NFILES=131072
MEMLOCK=82000
DAEMON_OPTS="-a :${port} \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s file,/var/lib/varnish/default/varnish_storage.bin,1G"
EOF

juju-log "reloading varnish configuration"
service varnish reload || :

juju-log "opening varnish port"
open-port $port/tcp
