#!/bin/sh
juju-log "${JUJU_REMOTE_UNIT} departed"

LOCAL_CONFIG_FILE="/etc/varnish/default.vcl"
UNIT_NAME=$(echo $JUJU_REMOTE_UNIT | sed -e "s/\///")

juju-log "Removing ${JUJU_REMOTE_UNIT} from varnish rotation"

sed -i "/^backend ${UNIT_NAME}/,/^\}/d" $LOCAL_CONFIG_FILE
sed -i "0,/\.backend \= ${UNIT_NAME}/{//d;}" $LOCAL_CONFIG_FILE

members=$(relation-list)

if [ -z "${members}" ]; then
    > /etc/varnish/default.vcl
    service varnish stop
else
    service varnish reload || service varnish restart
fi
